function IDRESULTSCutting10 = IMPORT_ID_Resultsv2(filename, dataLines)
%IMPORTFILE Import data from a text file
%  IDRESULTSCUTTING10 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  IDRESULTSCUTTING10 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  IDRESULTSCutting10 = importfile("C:\Users\adpatrick\OneDrive - nih.no\Desktop\Oslo2021\Intensity1\P001\ID_RESULTS_Cutting10.sto", [8, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 06-Oct-2023 19:20:05

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [8, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 28);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["time", "pelvis_tilt_moment", "pelvis_list_moment", "pelvis_rotation_moment", "pelvis_tx_force", "pelvis_ty_force", "pelvis_tz_force", "hip_flexion_r_moment", "hip_adduction_r_moment", "hip_rotation_r_moment", "hip_flexion_l_moment", "hip_adduction_l_moment", "hip_rotation_l_moment", "lumbar_extension_moment", "lumbar_bending_moment", "lumbar_rotation_moment", "knee_angle_r_moment", "knee_angle_l_moment", "knee_varus_med_r_moment", "knee_varus_med_l_moment", "knee_valgus_lat_r_moment", "knee_valgus_lat_l_moment", "ankle_angle_r_moment", "ankle_angle_l_moment", "subtalar_angle_r_moment", "subtalar_angle_l_moment", "mtp_angle_r_moment", "mtp_angle_l_moment"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
IDRESULTSCutting10 = readtable(filename, opts);

end